# Generated by Django 4.2.2 on 2023-06-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_alter_proposalfieldvalue_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalfieldvalue',
            name='value',
            field=models.CharField(blank=True, help_text='Value of the field', max_length=300),
        ),
    ]
