version: "3.7"

services:
  postgres:
    container_name: proposal_postgres
    image: postgres:15-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    # ports:  # only for dev
    # - "5432:5432"  
    env_file:
      - test.env
    networks:
      - proposal_dev

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: proposal_rabbitmq
    restart: unless-stopped
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
    ports:
      - "15672:15672"
      # - "5672:5672"  # only for dev
    networks:
      - proposal_dev
    env_file:
      - test.env

  proposal_backend:
    container_name: proposal_backend
    build:
      context: ./backend
    command: sh /code/start.sh

      - proposal_backend-static:/code/static
    ports:
      - "8000:8000"
    env_file:
      - test.env
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - proposal_dev

  celery:
    container_name: proposal_celery
    build:
      context: ./backend
    command: bash -c 'celery -A backend worker -l INFO'

    depends_on:
      - postgres
      - rabbitmq
    networks:
      - proposal_dev
    env_file:
      - test.env

  proposal_frontend:
    container_name: proposal_frontend
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    env_file:
      - test.env
    depends_on:
      - proposal_backend
    networks:
      - proposal_dev

networks:
  proposal_dev:


volumes:
  pg-data:
  proposal_backend-static:
  rabbitmq-data:
