# Generated by Django 4.2 on 2023-06-18 03:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('DENIED', 'DENIED'), ('PENDING', 'PENDING')], default='PENDING', max_length=8)),
                ('analyzed_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'loan proposal',
                'verbose_name_plural': 'Loan proposals',
            },
        ),
        migrations.CreateModel(
            name='ProposalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('checkbox', 'checkbox')], default='text', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'proposal',
                'verbose_name_plural': 'proposals',
            },
        ),
        migrations.CreateModel(
            name='ProposalFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=300)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='proposals.proposalfield')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='proposals.loanproposal')),
            ],
            options={
                'verbose_name': 'proposal field value',
                'verbose_name_plural': 'proposal field values',
            },
        ),
    ]
