# Generated by Django 4.2 on 2023-06-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanproposal',
            options={'verbose_name': 'Loan Proposal', 'verbose_name_plural': 'Loan Proposals'},
        ),
        migrations.AlterModelOptions(
            name='proposalfield',
            options={'verbose_name': 'Proposal Field', 'verbose_name_plural': 'Proposal Fields'},
        ),
        migrations.AlterModelOptions(
            name='proposalfieldvalue',
            options={'verbose_name': 'Proposal Field Value', 'verbose_name_plural': 'Proposal Field Values'},
        ),
        migrations.AlterField(
            model_name='loanproposal',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
