# Generated by Django 4.2 on 2023-06-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_alter_loanproposal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalfield',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
